Document: n2n
Title: Debian n2n Manual
Author: <insert document author here>
Abstract: This manual describes what n2n is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/n2n/n2n.sgml.gz

Format: postscript
Files: /usr/share/doc/n2n/n2n.ps.gz

Format: text
Files: /usr/share/doc/n2n/n2n.text.gz

Format: HTML
Index: /usr/share/doc/n2n/html/index.html
Files: /usr/share/doc/n2n/html/*.html

  
